import { Boss } from "../../models/Bosses";

export const bosses: Record<string, Boss> = {
  cemeteryShadeCaelid: {
    name: "Cemetery Shade",
    image: "image/image.png",
    description:
      "A Cemetery Shade can be found deep within Tombsward Catacombs in Limgrave.",
    location: "Caelid Catacombs",
    itemDrops: ["Lhutel the Headless", "Twinsage Sorcerer"],
    runeRewards: "2640 - 4200 (NG)",
    healthPoints: "",
    affectedBy: [],
    weakness: ["Holy"],
    resistance: ["Pierce"],
    immune: ["Bleed", "Frost", "Scarlet Rot", "Sleep", "Poison", "Madness"],
    moreInfo: false,
    completed: false,
  },
  commanderOneil: {
    name: "Commander O'Neil",
    image: "../assets/boss-images/commander-oneil.png",
    description:
      "Commander O'Neil can be found in the Swamp of Aeonia, just south of the Inner Aeonia Site of Grace. If you approach from the west, you may encounter Millicent. Instead, go around to the north of the swamp and come down, stopping at the Inner Aeonia Site of Grace on your way.",
    location: "Swamp of Aeonia, Caelid",
    itemDrops: ["Unalloyed Gold Needle"],
    runeRewards: "12000 (NG)",
    healthPoints: "",
    affectedBy: ["Bleed", "Frost", "Poison", "Sleep"],
    weakness: ["Magic", "Fire", "Thrust"],
    resistance: ["Slash", "Bleed", "Frost", "Sleep", "Poison"],
    immune: ["Scarlet Rot", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  crucibleKnightAndMisbegotten: {
    name: "Crucible Knight & Misbegotten Warrior",
    image: "../assets/boss-images/commander-oneil.png",
    description:
      "Crucible Knight and Misbegotten Warrior is a Field Boss in Elden Ring. A fearsome Misbegotten and a stoic knight have come to Redmane Castle to test their strength. This is an optional boss as players don't need to defeat it to advance.",
    location: "Redmane Castle, Caelid",
    itemDrops: ["Ruins Greatsword"],
    runeRewards: "16000 (NG)",
    healthPoints: "",
    affectedBy: ["Bleed", "Frost", "Poison", "Sleep"],
    weakness: ["Magic", "Fire", "Thrust"],
    resistance: ["Slash", "Bleed", "Frost", "Sleep", "Poison"],
    immune: ["Scarlet Rot", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  deathRiteBirdCaelid: {
    name: "Death Rite Bird (Caelid)",
    image: "../assets/boss-images/death-rite-bird.png",
    description: "Death Rite Bird can be found in Caelid.",
    location: "Caelid",
    itemDrops: ["Death's Poker"],
    runeRewards: "15000 (NG)",
    healthPoints: "",
    affectedBy: ["Scarlet Rot"],
    weakness: ["Strike", "Holy"],
    resistance: ["Lightning", "Scarlet Rot", "Thrust"],
    immune: ["Bleed", "Frost", "Sleep", "Poison", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  decayingEkzykes: {
    name: "Decaying Ekzykes",
    image: "../assets/boss-images/ekzykes.png",
    description:
      "You can find Decaying Ekzykes by following the Caelid Highway to the south. The dragon is sleeping in a small clearing close to the Cathedral of the Dragon Communion.",
    location: "Caelid",
    itemDrops: ["Dragon Heart"],
    runeRewards: "38000 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost"],
    weakness: [
      "Standard",
      "Strike",
      "Slash",
      "Magic",
      "Fire",
      "Holy",
      "Lightning",
      "Thrust",
    ],
    resistance: ["Scarlet Rot", "Poison"],
    immune: ["Sleep", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  erdtreeAvatarCaelid: {
    name: "Erdtree Avatar (Caelid)",
    image: "../assets/boss-images/erdtree-avatar.png",
    description:
      "Erdtree Avatar can be found in Caelid near the Minor Erdtree.",
    location: "Caelid",
    itemDrops: ["Greenburst Crystal Tear", "Flame-Shrouding Cracked Tear"],
    runeRewards: "6000 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Frost"],
    weakness: ["Fire"],
    resistance: ["Holy", "Scarlet Rot", "Poison"],
    immune: ["Bleed", "Sleep", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  erdtreeBurialWatchdogMinorErdtree: {
    name: "Erdtree Burial Watchdog (Duo)",
    image: "image/image.png",
    description:
      "Erdtree Burial Watchdogs are Field Bosses in Elden Ring. These catlike hounds guard catacombs throughout the Lands Between, wielding swords and staves as well as elemental magic. These are optional bosses, meaning players don't need to defeat them in order to advance.",
    location: "Minor Erdtree Catacombs, Caelid",
    itemDrops: ["Mad Pumpkin Head Ashes"],
    runeRewards: "7400",
    healthPoints: "",
    affectedBy: [],
    weakness: ["Strike"],
    resistance: [
      "Standard",
      "Slash",
      "Fire",
      "Holy",
      "Lightning",
      "Bleed",
      "Frost",
      "Scarlet Rot",
      "Poison",
      "Thrust",
    ],
    immune: [],
    moreInfo: false,
    completed: false,
  },
  fallingstarBeast: {
    name: "Fallingstar Beast",
    image: "../assets/boss-images/fallingstar-beast.png",
    description:
      "The Fallingstar Beast is encountered as the boss of the Sellia Crystal Tunnel located in Caelid, which you can access by heading to the entrance in the Swamp of Aeonia or by using the booby-trapped chest in Dragon-Burnt Ruins.",
    location: "Sellia Crystal Tunnel, Caelid",
    itemDrops: [
      "Gravity Stone Chunk",
      "Smithing Stone 7",
      "Somber Smithing Stone 6",
      "Somberstone Miner's Bell Bearing 1",
    ],
    runeRewards: "7800 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot"],
    weakness: ["Magic", "Fire", "Holy", "Lightning"],
    resistance: [
      "Standard",
      "Strike",
      "Slash",
      "Scarlet Rot",
      "Poison",
      "Thrust",
    ],
    immune: ["Bleed", "Frost", "Sleep", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  frenziedDuelist: {
    name: "Frenzied Duelist",
    image: "../assets/boss-images/frenzied-duelist.png",
    description:
      "Frenzied Duelist can be found at the Gaol Cave in Caelid, near the Astray from Caelid Highway North Site of Grace.",
    location: "Gaol Cave, Caelid",
    itemDrops: ["Putrid Corpse"],
    runeRewards: "6700 (NG)",
    healthPoints: "",
    affectedBy: ["Bleed", "Frost", "Scarlet Rot", "Poison", "Sleep"],
    weakness: ["Slash", "Bleed", "Frost", "Poison"],
    resistance: [],
    immune: ["Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  madPumpkinHead: {
    name: "Mad Pumpkin Head (Duo)",
    image: "image/image.png",
    description:
      "Mad Pumpkin Head is a Field Boss in Elden Ring. These towering humanoids wield massive weapons and wear distinctive pumpkin-shaped helmets. These are optional bosses as players are not required to defeat them to advance in Elden Ring.",
    location: "Caelem Ruins, Caelid",
    itemDrops: [],
    runeRewards: "1100 (NG)",
    healthPoints: "1325 (NG)",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost", "Sleep"],
    weakness: ["Slash", "Lightning", "Thrust"],
    resistance: ["Sleep"],
    immune: ["Madness"],
    moreInfo: false,
    completed: false,
  },
  magmaWyrmGaelTunnel: {
    name: "Magma Wyrm",
    image: "file-GeIcDkMaEOeIeUh3U88ENEP5",
    description: "Magma Wyrm can be found in the Gael Tunnel in Caelid.",
    location: "Gael Tunnel, Caelid",
    itemDrops: ["Moonveil", "Dragon Heart"],
    runeRewards: "7500 (NG)",
    healthPoints: "",
    affectedBy: ["Bleed"],
    weakness: [],
    resistance: [],
    immune: ["Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  nightsCavalryCaelid: {
    name: "Night's Cavalry (Caelid)",
    image: "image/image.png",
    description:
      "The different Night's Cavalry bosses can only be found at night. There are nine of them in total that can be fought across the Lands Between.",
    location: "Caelid",
    itemDrops: ["Ash of War: Giant Hunt"],
    runeRewards: "2800 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost"],
    weakness: [],
    resistance: [
      "Standard",
      "Strike",
      "Slash",
      "Fire",
      "Holy",
      "Bleed",
      "Frost",
      "Scarlet Rot",
      "Poison",
    ],
    immune: ["Madness"],
    moreInfo: false,
    completed: false,
  },
  noxSwordstressAndNoxPriest: {
    name: "Nox Swordstress & Nox Priest",
    image: "../assets/boss-images/nox.png",
    description:
      "Before challenging this boss you must first light all the torches in Sellia to break the seal blocking your way. Lighting these torches will also unlock other seals within the town which contain other items, so be sure to check those locations once the seals are broken too.",
    location: "Sellia, Town of Sorcery, Caelid",
    itemDrops: ["Nox Flowing Sword"],
    runeRewards: "6400 (NG)",
    healthPoints: "",
    affectedBy: [],
    weakness: [],
    resistance: [],
    immune: [],
    moreInfo: false,
    completed: false,
  },
  starscourgeRadahn: {
    name: "Starscourge Radahn",
    image: "path/to/image.png",
    description:
      "Starscourge Radahn can be found through a portal at Redmane Castle in Caelid. The nearest Site of Grace is the Chamber Outside the Plaza, but there is a Stake of Marika near the Boss Area portal.",
    location: "Redmane Castle, Caelid",
    itemDrops: ["Radahn's Great Rune", "Remembrance of the Starscourge"],
    runeRewards: "70000 (NG)",
    healthPoints: "",
    affectedBy: ["Bleed", "Poison", "Scarlet Rot"],
    weakness: ["Scarlet Rot"],
    resistance: ["Holy"],
    immune: [],
    moreInfo: false,
    completed: false,
  },
};
