import { Boss } from "../../models/Bosses";

export const bosses: Record<string, Boss> = {
  abductorVirgins: {
    name: "Abductor Virgins (Duo)",
    image: "../assets/boss-images/abductors.png",
    description: "",
    location: "Volcano Manor, Mt. Gelmir",
    itemDrops: ["Inquisitor's Girandole"],
    runeRewards: "10000 (NG)",
    healthPoints: "",
    affectedBy: [],
    weakness: [],
    resistance: [],
    immune: ["Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  demiHumanQueenMaggie: {
    name: "Demi-Human Queen Maggie",
    image: "../assets/boss-images/maggie.png",
    description:
      "Demi-Human Queen Maggie can be found behind the Hermit Village, near the Primeval Sorcerer Azur Site of Grace.",
    location: "Hermit Village, Mt. Gelmir",
    itemDrops: ["Memory Stone"],
    runeRewards: "13000 (NG)",
    healthPoints: "",
    affectedBy: ["Bleed", "Frost", "Scarlet Rot", "Poison", "Sleep"],
    weakness: ["Slash", "Fire", "Scarlet Rot", "Poison"],
    resistance: [],
    immune: ["Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  demiHumanQueenMargot: {
    name: "Demi-Human Queen Margot",
    image: "../assets/boss-images/margot.png",
    description:
      "Demi-Human Queen Margot is located at the end of Volcano Cave. This area is found across the bridge from the Ninth Mt. Gelmir Campsite.",
    location: "Volcano Cave, Mt. Gelmir",
    itemDrops: ["Jar Cannon"],
    runeRewards: "11000 (NG)",
    healthPoints: "",
    affectedBy: ["Bleed", "Frost", "Scarlet Rot", "Poison", "Sleep"],
    weakness: ["Slash", "Fire", "Scarlet Rot", "Poison"],
    resistance: [],
    immune: ["Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  fullGrownFallingstarBeast: {
    name: "Full-Grown Fallingstar Beast",
    image: "path/to/image.png",
    description:
      "The Full-Grown Fallingstar Beast can be found at a crater near the Ninth Mt. Gelmir Campsite, in Altus Plateau. You'll need to use a Spirit Spring to reach the area.",
    location: "Mt. Gelmir",
    itemDrops: [
      "Fallingstar Beast Jaw",
      "Smithing Stone 6",
      "Somber Smithing Stone 6",
    ],
    runeRewards: "21000 (NG)",
    healthPoints: "", // Not provided in the image
    affectedBy: ["Poison", "Scarlet Rot"],
    weakness: ["Magic", "Fire", "Holy", "Lightning"],
    resistance: ["Standard", "Scarlet Rot", "Poison"],
    immune: ["Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  rykardLordOfBlasphemy: {
    name: "Rykard, Lord of Blasphemy",
    image: "path/to/image.png",
    description:
      "Rykard, Lord of Blasphemy can be found deep in Volcano Manor, which is situated at the top of Mount Gelmir, in the Altus Plateau region. Rykard's boss room is separated from the rest of the area, and can only be entered via a waygate portal. After defeating the Godskin Noble, make your way north from the Temple of Eiglay Site of Grace, and find the waygate portal to Rykard's boss room.",
    location: "Volcano Manor, Mt. Gelmir",
    itemDrops: ["Remembrance of the Blasphemous", "Rykard's Great Rune"],
    runeRewards: "130000 (NG)",
    healthPoints: "",
    affectedBy: ["Bleed", "Frostbite", "Poison", "Scarlet Rot"],
    weakness: ["Frost"],
    resistance: ["Magic", "Fire", "Holy"],
    immune: [],
    moreInfo: false,
    completed: false,
  },
  godskinNobleVolcanoManor: {
    name: "Godskin Noble (Volcano Manor)",
    image: "../assets/boss-images/godskin-noble.png",
    description: "Godskin Noble can be found in Volcano Manor, Altus Plateau.",
    location: "Volcano Manor, Mt. Gelmir",
    itemDrops: ["Godskin Stitcher", "Noble Presence"],
    runeRewards: "5000 (NG)",
    healthPoints: "",
    affectedBy: ["Bleed", "Frost", "Scarlet Rot", "Poison"],
    weakness: ["Bleed", "Frost", "Sleep"],
    resistance: ["Fire", "Holy"],
    immune: ["Scarlet Rot", "Poison", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  kindredOfRot: {
    name: "Kindred of Rot (Duo)",
    image: "../assets/boss-images/kindred-of-rot.png",
    description:
      "The Kindreds of Rot can be found at the end of the Seethewater Cave. You can reach this area by starting from the Seethewater River Site of Grace and just following along the nearby path.",
    location: "Seethewater Cave, Mt. Gelmir",
    itemDrops: ["Kindred of Rot's Exultation"],
    runeRewards: "10000 (NG)",
    healthPoints: "",
    affectedBy: ["Bleed", "Frost", "Poison", "Scarlet Rot"],
    weakness: ["Fire", "Bleed", "Frost"],
    resistance: ["Scarlet Rot", "Poison"],
    immune: ["Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  magmaWyrmFortLaiedd: {
    name: "Magma Wyrm",
    image: "file-GeIcDkMaEOeIeUh3U88ENEP5",
    description: "Magma Wyrm can be found in Fort Laiedd in Mt. Gelmir.",
    location: "Fort Laiedd, Mt. Gelmir",
    itemDrops: ["Moonveil", "Dragon Heart"],
    runeRewards: "7500 (NG)",
    healthPoints: "",
    affectedBy: ["Bleed"],
    weakness: [],
    resistance: [],
    immune: ["Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  redWolfOfTheChampion: {
    name: "Red Wolf of the Champion",
    image: "path/to/image.png",
    description:
      "Red Wolf of the Champion can be found at the end of Gelmir Hero's Grave. If you've found the Primeval Sorcerer Azur Site of Grace, you can just hop down from the nearby rock formation.",
    location: "Gelmir Hero's Grave, Mt. Gelmir",
    itemDrops: ["Bloodhound Knight Floh"],
    runeRewards: "21000 (NG)",
    healthPoints: "", // Not provided in the image
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost"],
    weakness: ["Standard", "Strike", "Slash", "Pierce"],
    resistance: ["Magic", "Bleed", "Frost"],
    immune: ["Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  ulceratedTreeSpiritMountGelmirMinorErdtree: {
    name: "Ulcerated Tree Spirit",
    image: "path/to/image.png",
    description:
      "Ulcerated Tree Spirit can be found at the Minor Erdtree in Mount Gelmir.",
    location: "Mount Gelmir (Minor Erdtree)",
    itemDrops: ["Cerulean Hidden Tear", "Leaden Hardtear"],
    runeRewards: "16000",
    healthPoints: "", // Not provided in the image
    affectedBy: ["Poison", "Scarlet Rot", "Frost", "Sleep"],
    weakness: ["Fire", "Frost"],
    resistance: ["Holy", "Bleed", "Scarlet Rot", "Poison"],
    immune: ["Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
};
