import { Boss } from "../../models/Bosses";

export const bosses: Record<string, Boss> = {
  beastmanOfFarumAzulaGroveside: {
    name: "Beastman of Farum Azula",
    image: "image/image.png",
    description:
      "Beastman of Farum Azula is found in Groveside Cave in the Limgrave region.",
    location: "Groveside Cave, Limgrave",
    itemDrops: ["Flamedrake Talisman"],
    runeRewards: "1000 (NG)",
    healthPoints: "1417 (NG)",
    affectedBy: ["Poison", "Scarlet Rot", "Sleep", "Bleed", "Frost"],
    weakness: ["Slash", "Fire"],
    resistance: ["Bleed", "Frost"],
    immune: ["Madness"],
    moreInfo: false,
    completed: false,
  },
  bellBearingHunterWarmastersShack: {
    name: "Bell Bearing Hunter (Warmaster's Shack)",
    image: "../assets/boss-images/bell-bearing-hunter.png",
    description:
      "Bell Bearing Hunter can be found at the Warmaster's Shack in Limgrave. Each one only spawns at night.",
    location: "Warmaster's Shack, Limgrave",
    itemDrops: ["Bone Peddler's Bell Bearing"],
    runeRewards: "50000 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost"],
    weakness: [],
    resistance: [
      "Standard",
      "Strike",
      "Slash",
      "Fire",
      "Holy",
      "Bleed",
      "Frost",
      "Scarlet Rot",
      "Sleep",
      "Poison",
    ],
    immune: ["Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  blackKnifeAssassin: {
    name: "Black Knife Assassin",
    image: "image/image.png",
    description:
      "Black Knife Assassin can be found in Deathtouched Catacombs, in the northeastern part of Limgrave.",
    location: "Deathtouched Catacombs, Limgrave",
    itemDrops: [
      "Black Knife",
      "Assassin's Cerulean Dagger",
      "Assassin's Crimson Dagger",
      "Black Knifprint",
    ],
    runeRewards: "1000 (NG)",
    healthPoints: "1001 (NG)",
    affectedBy: ["Frost"],
    weakness: [],
    resistance: ["Holy", "Thrust"],
    immune: ["Bleed", "Scarlet Rot", "Sleep", "Poison", "Madness"],
    moreInfo: false,
    completed: false,
  },
  bloodhoundKnightDarriwil: {
    name: "Bloodhound Knight Darriwil",
    image: "image/image.png",
    description:
      "Bloodhound Knight Darriwil is located at the Forlon Hound Evergaol in Stormhill. Look for a blue platform at the end of the road, south of the Site of Grace. Interacting with it will lead you to where Bloodhound Knight Darriwil is.",
    location: "Forlon Hound Evergaol, Limgrave",
    itemDrops: ["Bloodhound's Fang"],
    runeRewards: "1400 (NG)",
    healthPoints: "",
    affectedBy: ["Sleep"],
    weakness: ["Lightning"],
    resistance: ["Bleed", "Frost", "Scarlet Rot", "Poison"],
    immune: ["Madness"],
    moreInfo: false,
    completed: false,
  },
  crucibleKnightStormhillEvergaol: {
    name: "Crucible Knight (Stormhill Evergaol)",
    image: "image/image.png",
    description:
      "Crucible Knight is within Stormhill Evergaol, up on the cliffs towering above Gatefront Ruins. We recommend heading there from the Warmaster's Shack site of grace instead the one nearest to it (Gatefront) because the path is safer.",
    location: "Stormhill Evergaol, Limgrave",
    itemDrops: ["Aspects of the Crucible: Tail"],
    runeRewards: "2100 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Frost", "Sleep"],
    weakness: [],
    resistance: [
      "Standard",
      "Strike",
      "Slash",
      "Holy",
      "Frost",
      "Scarlet Rot",
      "Sleep",
      "Poison",
      "Thrust",
    ],
    immune: ["Bleed", "Madness"],
    moreInfo: false,
    completed: false,
  },
  deathbirdWestLimgrave: {
    name: "Deathbird (West Limgrave)",
    image: "image/image.png",
    description:
      "The Deathbird in West Limgrave can be found east of the Warmaster's Shack.",
    location: "West Limgrave",
    itemDrops: ["Blue-Feathered Branchsword"],
    runeRewards: "2800 (NG)",
    healthPoints: "",
    affectedBy: ["Scarlet Rot"],
    weakness: ["Strike", "Slash", "Holy"],
    resistance: ["Lightning", "Thrust"],
    immune: ["Bleed", "Frost", "Sleep", "Poison", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  demiHumanChief: {
    name: "Demi-Human Chief",
    image: "image/image.png",
    description:
      "The Demi-Human Chief is located inside the Coastal Cave in Limgrave. Trace the coastline all the way to where the cave marker is on the map provided. The cave itself is mostly dark, so make sure you bring either a Torch or Lantern before venturing inside.",
    location: "Coastal Cave, Limgrave",
    itemDrops: ["Sewing Needle", "Tailoring Tools"],
    runeRewards: "900 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost", "Sleep"],
    weakness: [
      "Standard",
      "Strike",
      "Slash",
      "Fire",
      "Holy",
      "Frost",
      "Thrust",
    ],
    resistance: ["Bleed", "Frost", "Sleep"],
    immune: ["Madness"],
    moreInfo: false,
    completed: false,
  },
  erdtreeBurialWatchdogStormfront: {
    name: "Erdtree Burial Watchdog",
    image: "image/image.png",
    description:
      "An Erdtree Burial Watchdog is the boss of Stormfoot Catacombs located northwest of the Church of Elleh in Limgrave.",
    location: "Stormfoot Catacombs, Limgrave",
    itemDrops: [
      "Noble Sorcerer Ashes",
      "Impalers Catacombs",
      "Morphed Catacombs",
      "Cilfailog Catacombs",
      "Wyndham Catacombs",
    ],
    runeRewards:
      "1300 (Stormfoot Catacombs), 1600 (Impalers Catacombs), 2400 (Cliffbottom Catacombs), 2600 (Morphed Catacombs), 3600 (Wyndham Catacombs)",
    healthPoints: "",
    affectedBy: [],
    weakness: ["Strike"],
    resistance: [
      "Standard",
      "Slash",
      "Fire",
      "Holy",
      "Lightning",
      "Bleed",
      "Frost",
      "Scarlet Rot",
      "Poison",
      "Thrust",
    ],
    immune: [],
    moreInfo: false,
    completed: false,
  },
  flyingDragonAgheel: {
    name: "Flying Dragon Agheel",
    image: "image/image.png",
    description: "The boss is located in the Dragon-Burnt Ruins in Limgrave.",
    location: "Dragon-Burnt Ruins, Limgrave",
    itemDrops: ["Dragon Heart"],
    runeRewards: "7000 (NG)",
    healthPoints: "3200 (NG)",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost"],
    weakness: [],
    resistance: [
      "Standard",
      "Strike",
      "Slash",
      "Fire",
      "Holy",
      "Lightning",
      "Bleed",
      "Frost",
      "Scarlet Rot",
      "Poison",
    ],
    immune: ["Sleep", "Madness"],
    moreInfo: false,
    completed: false,
  },
  godrickTheGrafted: {
    name: "Godrick the Grafted",
    image: "path/to/image.png",
    description:
      "Godrick the Grafted is located towards the final area of Stormveil Castle.",
    location: "Stormveil Castle, Limgrave",
    itemDrops: ["Godrick's Great Rune", "Remembrance of the Grafted"],
    runeRewards: "20000 (NG)",
    healthPoints: "6080 (NG)",
    affectedBy: ["Poison", "Bleed", "Scarlet Rot", "Frost", "Sleep"],
    weakness: ["Bleed", "Frost", "Scarlet Rot", "Sleep", "Poison"],
    resistance: ["Holy"],
    immune: ["Madness"],
    moreInfo: false,
    completed: false,
  },
  graftedScion: {
    name: "Grafted Scion",
    image: "image/image.png",
    description:
      "This boss is the tutorial boss found in the Chapel of Anticipation in Limgrave. Even if it is undefeated during the tutorial, you can return here via one of the portals at the Four Belfries.",
    location: "Chapel of Anticipation, Limgrave",
    itemDrops: ["Ornamental Straight Sword"],
    runeRewards: "3200 (NG)",
    healthPoints: "2596 (NG)",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost", "Sleep"],
    weakness: ["Slash"],
    resistance: ["Scarlet Rot", "Poison"],
    immune: ["Madness"],
    moreInfo: false,
    completed: false,
  },
  graveWardenDuelistMurkwater: {
    name: "Grave Warden Duelist",
    image: "image/image.png",
    description:
      "You can find the Grave Warden Duelist in the Murkwater Catacombs at Limgrave. After arriving through the doors, go down the stairs and you will see a Site of Grace. After 2 sets of stairs, turn right and go down the corridor. Traverse the mist and you will see Grave Warden Duelist waiting for you.",
    location: "Murkwater Catacombs, Limgrave",
    itemDrops: ["Battle Hammer", "Banished Knight Engrave"],
    runeRewards: "1700 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost", "Sleep"],
    weakness: ["Slash"],
    resistance: ["Fire", "Holy", "Lightning"],
    immune: ["Madness"],
    moreInfo: false,
    completed: false,
  },
  guardianGolemHighroadCave: {
    name: "Guardian Golem (Highroad Cave)",
    image: "image/image.png",
    description:
      "The Optional Guardian Golem boss can be found in Highroad Cave, which is a slightly hidden cave north of Limgrave. You can get here by traveling along the river northward.",
    location: "Highroad Cave, Limgrave",
    itemDrops: ["Blue Dancer Charm"],
    runeRewards: "1700 (NG)",
    healthPoints: "",
    affectedBy: [],
    weakness: [],
    resistance: ["Fire", "Holy", "Lightning"],
    immune: ["Poison", "Sleep", "Scarlet Rot", "Frost", "Bleed"],
    moreInfo: false,
    completed: false,
  },
  madPumpkinHead: {
    name: "Mad Pumpkin Head",
    image: "image/image.png",
    description:
      "Pumpkin Head can be found underground in the Waypoint Ruins area. The entrance is in a narrow alley in the center of the ruins.",
    location: "Waypoint Ruins, Limgrave",
    itemDrops: [],
    runeRewards: "1100 (NG)",
    healthPoints: "1325 (NG)",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost", "Sleep"],
    weakness: ["Slash", "Lightning", "Thrust"],
    resistance: ["Sleep"],
    immune: ["Madness"],
    moreInfo: false,
    completed: false,
  },
  margitTheFellOmen: {
    name: "Margit the Fell Omen",
    image: "path/to/image.png",
    description:
      "Margit is the first Main Boss that can be found in Stormhill near the entrance to the Legacy Dungeon Stormveil Castle. The closest Site of Grace to him is the Castleward Tunnel.",
    location: "Stormveil Castle, Limgrave",
    itemDrops: ["Talisman Pouch"],
    runeRewards: "12000 (NG), 60000 (NG+1)",
    healthPoints: "4174 (NG)",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost", "Sleep"],
    weakness: ["Slash", "Pierce", "Holy"],
    resistance: [],
    immune: [],
    moreInfo: false,
    completed: false,
  },
  nightsCavalryLimgrave: {
    name: "Night's Cavalry (Limgrave)",
    image: "image/image.png",
    description:
      "The different Night's Cavalry bosses can only be found at night. There are nine of them in total that can be fought across the Lands Between.",
    location: "Limgrave",
    itemDrops: ["Ash of War: Barricade Shield"],
    runeRewards: "2800 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost"],
    weakness: [],
    resistance: [
      "Standard",
      "Strike",
      "Slash",
      "Fire",
      "Holy",
      "Bleed",
      "Frost",
      "Scarlet Rot",
      "Poison",
    ],
    immune: ["Madness"],
    moreInfo: false,
    completed: false,
  },
  patches: {
    name: "Patches",
    image: "image/image.png",
    description:
      "Patches will yield about half way through the fight and plead for his life. You'll know he's given in when he ducks under his shield and shouts, 'I surrender!' Should you let him live, the next time you visit the cave, he will open up a secret shop where you can buy Margit's Shackles, an item that will help a lot in your fight with the first required boss, Margit. You'll also unlock the Grovel for Mercy Gesture. For these reasons, it's recommended that you let Patches live.\n\nIf you decide to kill Patches, you'll receive a Spear+7 and Leather Armor.",
    location: "Murkwater Cave, Limgrave",
    itemDrops: ["Spear+7", "Leather Armor"],
    runeRewards: "800 (NG)",
    healthPoints: "1191 (NG)",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost"],
    weakness: ["Lightning", "Bleed", "Frost", "Scarlet Rot", "Poison"],
    resistance: [],
    immune: ["Sleep", "Madness"],
    moreInfo: false,
    completed: false,
  },
  soldierOfGodrick: {
    name: "Soldier of Godrick",
    image: "../assets/boss-images/soldier-of-godrick.png", // Replace with actual image path if necessary
    description:
      "Soldier of Godrick is located in Fringefolk Hero's Grave, down a pit you can jump into. You can skip Soldier of Godrick by heading onward up the stairs and past the Site of Grace.",
    location: "Stranded Graveyard, Limgrave",
    itemDrops: [],
    runeRewards: "400 (NG)",
    healthPoints: "384 (NG)",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost", "Sleep"],
    weakness: ["Lightning", "Thrust"],
    resistance: [],
    immune: ["Madness"],
    moreInfo: false,
    completed: false,
  },
  stonediggerTrollLimgrave: {
    name: "Stonedigger Troll",
    image: "image/image.png",
    description:
      "Stonedigger Troll can be found at the bottom of the Limgrave Tunnels in the Limgrave region. The boss room can be found behind two large wooden doors.",
    location: "Limgrave Tunnels, Limgrave",
    itemDrops: ["Great Club", "Roar Medallion"],
    runeRewards: "1800 (NG)",
    healthPoints: "1295 (NG)",
    affectedBy: ["Scarlet Rot", "Bleed", "Frost", "Sleep"],
    weakness: ["Magic", "Sleep"],
    resistance: [
      "Standard",
      "Slash",
      "Bleed",
      "Frost",
      "Scarlet Rot",
      "Poison",
      "Thrust",
    ],
    immune: ["Madness"],
    moreInfo: false,
    completed: false,
  },
  tibiaMarinerSummonwater: {
    name: "Tibia Mariner",
    image: "../assets/boss-images/tibia-mariner.png", // Replace with actual image path if necessary
    description:
      "Tibia Mariner is located in Summonwater Village, in the northeast of Limgrave.",
    location: "Summonwater Village, Limgrave",
    itemDrops: ["Deathroot", "Skeletal Militiaman Spirit Ash"],
    runeRewards: "2400 (NG)",
    healthPoints: "3176 (NG)",
    affectedBy: ["Scarlet Rot"],
    weakness: ["Strike", "Holy"],
    resistance: ["Thrust", "Scarlet Rot"],
    immune: ["Poison", "Bleed", "Frost", "Sleep", "Madness"],
    moreInfo: false,
    completed: false,
  },
  treeSentinelLimgrave: {
    name: "Tree Sentinel",
    image: "image/image.png",
    description:
      "The Tree Sentinel is an optional Field Boss located in the grassy plains of Limgrave, near the path between The First Step and the Church of Elleh Sites of Grace. You can see the Tree Sentinel in plain view as you talk to Varré for the first time.",
    location: "Limgrave",
    itemDrops: ["Golden Halberd", "Holy Ground"],
    runeRewards: "3200 (NG)",
    healthPoints: "2880 (NG)",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost", "Sleep"],
    weakness: ["Lightning"],
    resistance: ["Slash", "Holy", "Fire", "Scarlet Rot", "Poison", "Sleep"],
    immune: ["Madness"],
    moreInfo: false,
    completed: false,
  },
  ulceratedTreeSpiritFringefolkHerosGrave: {
    name: "Ulcerated Tree Spirit",
    image: "path/to/image.png",
    description:
      "Ulcerated Tree Spirit can be found in Fringefolk Hero's Grave.",
    location: "Fringefolk Hero's Grave, Limgrave",
    itemDrops: ["Golden Seed", "Banished Knight Oleg Ashes"],
    runeRewards: "15000",
    healthPoints: "", // Not provided in the image
    affectedBy: ["Poison", "Scarlet Rot", "Frost", "Sleep"],
    weakness: ["Fire", "Frost"],
    resistance: ["Holy", "Bleed", "Scarlet Rot", "Poison"],
    immune: ["Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
};
