import { Boss } from "../../models/Bosses";

export const bosses: Record<string, Boss> = {
  adanThiefOfFire: {
    name: "Adan, Thief of Fire",
    image: "../assets/boss-images/adan-thief-fire.png",
    description:
      "Adan, Thief of Fire can be found in Malefactor's Evergaol, which you can teleport to from a high cliff in Liurnia of the Lakes. Jump in the Spirit Spring and step into the portal to find him.",
    location: "Malefactor's Evergaol, Liurnia of the Lakes",
    itemDrops: ["Flame of the Fell God"],
    runeRewards: "3800 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost"],
    weakness: ["Lightning", "Bleed", "Frost", "Scarlet Rot", "Poison"],
    resistance: [],
    immune: ["Sleep", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  alabasterLord: {
    name: "Alabaster Lord",
    image: "../assets/boss-images/alabaster.png",
    description:
      "Alabaster Lord can be found at Royal Grave Evergaol, near Caria Manor, in West Liurnia. The nearest Site of Grace is Behind Caria Manor.",
    location: "Royal Grave Evergaol, Liurnia of the Lakes",
    itemDrops: ["Meteorite"],
    runeRewards: "3600 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Sleep"],
    weakness: [],
    resistance: ["Bleed", "Scarlet Rot", "Sleep", "Poison"],
    immune: ["Frost", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  alectoBlackKnifeRingleader: {
    name: "Alecto, Black Knife Ringleader",
    image: "../assets/boss-images/alecto.png",
    description:
      "Alecto, Black Knife Ringleader can be found at the Ringleader's Evergaol, in Western Liurnia of the Lakes. The nearest Site of Grace is the Moonlight Altar.",
    location: "Ringleader's Evergaol, Liurnia of the Lakes",
    itemDrops: ["Black Knife Tiche"],
    runeRewards: "80000 (NG)",
    healthPoints: "",
    affectedBy: ["Frost"],
    weakness: ["Frost"],
    resistance: ["Holy", "Thrust"],
    immune: [
      "Bleed",
      "Scarlet Rot",
      "Sleep",
      "Poison",
      "Madness",
      "Instant Death",
    ],
    moreInfo: false,
    completed: false,
  },
  bellBearingHunterChurchOfVows: {
    name: "Bell Bearing Hunter (Church of Vows)",
    image: "../assets/boss-images/bell-bearing-hunter.png",
    description:
      "Bell Bearing Hunter can be found at the Church of Vows in Liurnia of the Lakes. Each one only spawns at night.",
    location: "Church of Vows, Liurnia of the Lakes",
    itemDrops: ["Meat Peddler's Bell Bearing"],
    runeRewards: "2700 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost"],
    weakness: [],
    resistance: [
      "Standard",
      "Strike",
      "Slash",
      "Fire",
      "Holy",
      "Bleed",
      "Frost",
      "Scarlet Rot",
      "Sleep",
      "Poison",
    ],
    immune: ["Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  blackKnifeAssassinBlackKnifeCatacombs: {
    name: "Black Knife Assassin",
    image: "image/image.png",
    description:
      "Black Knife Assassin can be found in Deathtouched Catacombs, in the northeastern part of Limgrave.",
    location: "Black Knife Catacombs, Liurnia of the Lakes",
    itemDrops: [
      "Black Knife",
      "Assassin's Cerulean Dagger",
      "Assassin's Crimson Dagger",
      "Black Knifprint",
    ],
    runeRewards: "1000 (NG)",
    healthPoints: "1001 (NG)",
    affectedBy: ["Frost"],
    weakness: [],
    resistance: ["Holy", "Thrust"],
    immune: ["Bleed", "Scarlet Rot", "Sleep", "Poison", "Madness"],
    moreInfo: false,
    completed: false,
  },
  bloodhoundKnight: {
    name: "Bloodhound Knight",
    image: "../assets/boss-images/bloodhound-knight.png",
    description:
      "Bloodhound Knight is located in the deepest level of Lakeside Crystal Cave in Liurnia of the Lakes. You can see the path to deeper levels within the cave from the ledge where you fight the first and second set of Demi-Humans.",
    location: "Lakeside Crystal Cave, Liurnia of the Lakes",
    itemDrops: ["Cerulean Amber Medallion"],
    runeRewards: "4320 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost", "Sleep"],
    weakness: ["Lightning"],
    resistance: ["Bleed", "Frost", "Scarlet Rot", "Poison"],
    immune: ["Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  bolsCarianKnight: {
    name: "Bols, Carian Knight",
    image: "../assets/boss-images/bols-carian-knight.png",
    description:
      "Bols, Carian Knight can be found after using the portal in Cuckoo's Evergaol, in West Liurnia.",
    location: "Cuckoo's Evergaol, Liurnia of the Lakes",
    itemDrops: ["Greatblade Phalanx"],
    runeRewards: "4600 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost", "Sleep"],
    weakness: ["Slash", "Fire", "Sleep"],
    resistance: ["Bleed", "Frost", "Scarlet Rot", "Poison"],
    immune: ["Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  cemeteryShadeBlackKnife: {
    name: "Cemetery Shade",
    image: "image/image.png",
    description:
      "A Cemetery Shade can be found deep within Tombsward Catacombs in Limgrave.",
    location: "Black Knife Catacombs, Liurnia of the Lakes",
    itemDrops: ["Lhutel the Headless", "Twinsage Sorcerer"],
    runeRewards: "2640 - 4200 (NG)",
    healthPoints: "",
    affectedBy: [],
    weakness: ["Holy"],
    resistance: ["Pierce"],
    immune: ["Bleed", "Frost", "Scarlet Rot", "Sleep", "Poison", "Madness"],
    moreInfo: false,
    completed: false,
  },
  cleanrotKnightsStillwaterCave: {
    name: "Cleanrot Knights (Stillwater Cave)",
    image: "../assets/boss-images/cleanrot-knight.png",
    description:
      "Cleanrot Knights can be found in Stillwater Cave in Liurnia of the Lakes.",
    location: "Stillwater Cave, Liurnia of the Lakes",
    itemDrops: ["Winged Sword Insignia"],
    runeRewards: "7000 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Bleed", "Frost", "Sleep"],
    weakness: ["Fire", "Sleep"],
    resistance: ["Slash", "Holy", "Bleed", "Frost", "Poison"],
    immune: ["Scarlet Rot", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  crystalianRayaLucariaCrystalTunnel: {
    name: "Crystalian (Raya Lucaria Crystal Tunnel)",
    image: "../assets/boss-images/crystallian.png",
    description:
      "Crystalian can be found in the Raya Lucaria Crystal Tunnel in Liurnia of the Lakes.",
    location: "Raya Lucaria Crystal Tunnel, Liurnia of the Lakes",
    itemDrops: ["Smithing Stone (5)"],
    runeRewards: "3800 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Frost"],
    weakness: ["Blunt"],
    resistance: ["Slash", "Pierce", "Fire", "Magic", "Holy"],
    immune: ["Bleed", "Sleep", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  crystalianAcademyCrystalCave: {
    name: "Crystalian (Academy Crystal Cave)",
    image: "../assets/boss-images/crystallian.png",
    description:
      "Crystalian can be found in the Academy Crystal Cave in Liurnia of the Lakes.",
    location: "Academy Crystal Cave, Liurnia of the Lakes",
    itemDrops: ["Smithing Stone (5)"],
    runeRewards: "4200 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Frost"],
    weakness: ["Blunt"],
    resistance: ["Slash", "Pierce", "Fire", "Magic", "Holy"],
    immune: ["Bleed", "Sleep", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  deathRiteBirdLiurnia: {
    name: "Death Rite Bird (Liurnia of the Lakes)",
    image: "../assets/boss-images/death-rite-bird.png",
    description: "Death Rite Bird can be found in Liurnia of the Lakes.",
    location: "Liurnia of the Lakes",
    itemDrops: ["Ancient Death Rancor"],
    runeRewards: "7800 (NG)",
    healthPoints: "",
    affectedBy: ["Scarlet Rot"],
    weakness: ["Strike", "Holy"],
    resistance: ["Lightning", "Scarlet Rot", "Thrust"],
    immune: ["Bleed", "Frost", "Sleep", "Poison", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  deathbirdLiurniaOfTheLakes: {
    name: "Deathbird (Liurnia of the Lakes)",
    image: "image/image.png",
    description:
      "The Deathbird in Liurnia of the Lakes can be found in the Liurnia of the Lakes region.",
    location: "Liurnia of the Lakes",
    itemDrops: ["Red-Feathered Branchsword"],
    runeRewards: "6800 (NG)",
    healthPoints: "",
    affectedBy: ["Scarlet Rot"],
    weakness: ["Strike", "Slash", "Holy"],
    resistance: ["Lightning", "Thrust"],
    immune: ["Bleed", "Frost", "Sleep", "Poison", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  erdtreeAvatarEastLiurnia: {
    name: "Erdtree Avatar (East Liurnia)",
    image: "../assets/boss-images/erdtree-avatar.png",
    description:
      "Erdtree Avatar can be found in East Liurnia near the Minor Erdtree.",
    location: "East Liurnia, Liurnia of the Lakes",
    itemDrops: [
      "Magic-Shrouding Cracked Tear",
      "Lightning-Shrouding Cracked Tear",
      "Holy-Shrouding Cracked Tear",
    ],
    runeRewards: "4900 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Frost"],
    weakness: ["Fire"],
    resistance: ["Holy", "Scarlet Rot", "Poison"],
    immune: ["Bleed", "Sleep", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  erdtreeAvatarWestLiurnia: {
    name: "Erdtree Avatar (West Liurnia)",
    image: "../assets/boss-images/erdtree-avatar.png",
    description:
      "Erdtree Avatar can be found in West Liurnia near the Minor Erdtree.",
    location: "West Liurnia, Liurnia of the Lakes",
    itemDrops: ["Cerulean Crystal Tear", "Ruptured Crystal Tear"],
    runeRewards: "4900 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Frost"],
    weakness: ["Fire"],
    resistance: ["Holy", "Scarlet Rot", "Poison"],
    immune: ["Bleed", "Sleep", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  erdtreeBurialWatchdogCliff: {
    name: "Erdtree Burial Watchdog",
    image: "image/image.png",
    description:
      "An Erdtree Burial Watchdog is the boss of Stormfoot Catacombs located northwest of the Church of Elleh in Limgrave.",
    location: "Cliffbottom Catacombs, Liurnia of the Lakes",
    itemDrops: [
      "Noble Sorcerer Ashes",
      "Impalers Catacombs",
      "Morphed Catacombs",
      "Cilfailog Catacombs",
      "Wyndham Catacombs",
    ],
    runeRewards:
      "1300 (Stormfoot Catacombs), 1600 (Impalers Catacombs), 2400 (Cliffbottom Catacombs), 2600 (Morphed Catacombs), 3600 (Wyndham Catacombs)",
    healthPoints: "",
    affectedBy: [],
    weakness: ["Strike"],
    resistance: [
      "Standard",
      "Slash",
      "Fire",
      "Holy",
      "Lightning",
      "Bleed",
      "Frost",
      "Scarlet Rot",
      "Poison",
      "Thrust",
    ],
    immune: [],
    moreInfo: false,
    completed: false,
  },
  glintstoneDragonAdulaRannisRise: {
    name: "Glintstone Dragon Adula (Ranni's Rise)",
    image: "../assets/boss-images/glintstone-dragon-adula.png",
    description:
      "Glintstone Dragon Adula can initially be found in the area close to Ranni's Rise. This boss will escape if you lower it down to half its HP. It's not necessary to fight Glintstone Dragon Adula here, as it will appear at the Cathedral of Manus Celes anyway.",
    location: "Ranni's Rise, Liurnia of the Lakes",
    itemDrops: ["Dragon Heart", "Adula's Moonblade"],
    runeRewards: "120000 (NG)",
    healthPoints: "",
    affectedBy: ["Bleed", "Poison", "Scarlet Rot", "Frost"],
    weakness: ["Bleed", "Frost", "Scarlet Rot", "Poison"],
    resistance: [
      "Standard",
      "Strike",
      "Slash",
      "Magic",
      "Fire",
      "Holy",
      "Lightning",
    ],
    immune: ["Sleep", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  glintstoneDragonSmarag: {
    name: "Glintstone Dragon Smarag",
    image: "../assets/boss-images/glintstone-dragon.png",
    description:
      "Glintstone Dragon Smarag can be found sleeping beside a rock northwest of Temple Quarter, at the heart of Liurnia of the Lakes.",
    location: "Liurnia of the Lakes",
    itemDrops: ["Dragon Heart"],
    runeRewards: "16800 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost"],
    weakness: [],
    resistance: [
      "Standard",
      "Strike",
      "Slash",
      "Magic",
      "Fire",
      "Holy",
      "Lightning",
      "Bleed",
      "Frost",
      "Scarlet Rot",
      "Poison",
    ],
    immune: ["Sleep", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  magmaWyrmMakar: {
    name: "Magma Wyrm Makar",
    image: "../assets/boss-images/magma-wydm-makar.png",
    description:
      "Magma Wyrm Makar is found in the Ruin-Strewn Precipice, which is located in northern Liurnia. The nearest Site of Grace is the Ruin-Strewn Precipice Overlook, right outside the boss arena.",
    location: "Ruin-Strewn Precipice, Liurnia of the Lakes",
    itemDrops: ["Magma Wyrm's Scalesword", "Dragon Heart"],
    runeRewards: "24000 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost", "Sleep"],
    weakness: ["Sleep"],
    resistance: [
      "Slash",
      "Magic",
      "Fire",
      "Holy",
      "Lightning",
      "Bleed",
      "Frost",
      "Scarlet Rot",
      "Poison",
    ],
    immune: ["Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  nightsCavalryLiurniaSouth: {
    name: "Night's Cavalry (Liurnia South)",
    image: "image/image.png",
    description:
      "The different Night's Cavalry bosses can only be found at night. There are nine of them in total that can be fought across the Lands Between.",
    location: "Liurnia (South)",
    itemDrops: ["Ash of War: Bloodhound's Step"],
    runeRewards: "2800 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost"],
    weakness: [],
    resistance: [
      "Standard",
      "Strike",
      "Slash",
      "Fire",
      "Holy",
      "Bleed",
      "Frost",
      "Scarlet Rot",
      "Poison",
    ],
    immune: ["Madness"],
    moreInfo: false,
    completed: false,
  },
  nightsCavalryLiurniaNorth: {
    name: "Night's Cavalry (Liurnia North)",
    image: "image/image.png",
    description:
      "The different Night's Cavalry bosses can only be found at night. There are nine of them in total that can be fought across the Lands Between.",
    location: "Liurnia (North)",
    itemDrops: ["Ash of War: Ice Spear"],
    runeRewards: "2800 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost"],
    weakness: [],
    resistance: [
      "Standard",
      "Strike",
      "Slash",
      "Fire",
      "Holy",
      "Bleed",
      "Frost",
      "Scarlet Rot",
      "Poison",
    ],
    immune: ["Madness"],
    moreInfo: false,
    completed: false,
  },
  omenkillerVillageOfTheAlbinaurics: {
    name: "Omenkiller (Village of the Albinaurics)",
    image: "../assets/boss-images/omenkiller.png",
    description:
      "Omenkiller can be found at the Village of the Albinaurics, in West Liurnia. There is a Site of Grace in the village that you can spawn at.",
    location: "Village of the Albinaurics, Liurnia of the Lakes",
    itemDrops: ["Crucible Knot Talisman"],
    runeRewards: "4900 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost", "Sleep"],
    weakness: ["Bleed", "Frost", "Sleep"],
    resistance: ["Fire", "Scarlet Rot", "Poison"],
    immune: ["Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  redWolfOfRadagon: {
    name: "Red Wolf of Radagon",
    image: "path/to/image.png",
    description:
      "The Red Wolf of Radagon is encountered as a boss near the Schoolhouse Classroom Site of Grace at the Academy of Raya Lucaria, and is required to defeat to advance in the area.",
    location: "Academy of Raya Lucaria, Liurnia of the Lakes",
    itemDrops: ["Memory Stone"],
    runeRewards: "14000 (Academy of Raya Lucaria)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost", "Sleep"],
    weakness: ["Slash"],
    resistance: ["Magic"],
    immune: ["Sleep", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  rennalaQueenOfTheFullMoon: {
    name: "Rennala, Queen of the Full Moon",
    image: "path/to/image.png",
    description:
      "Rennala, Queen of the Full Moon can be found at the Academy of Raya Lucaria. The nearest Site of Grace is the Debate Parlor. You're required to defeat her in order to advance in the area.",
    location: "Academy of Raya Lucaria, Liurnia of the Lakes",
    itemDrops: [
      "Great Rune of the Unborn",
      "Remembrance of the Full Moon Queen",
    ],
    runeRewards: "40000 (NG)",
    healthPoints: "",
    affectedBy: ["Bleed", "Frostbite", "Poison", "Scarlet Rot"],
    weakness: ["Standard", "Strike", "Pierce"],
    resistance: ["Magic", "Fire", "Holy", "Lightning"],
    immune: [],
    moreInfo: false,
    completed: false,
  },
  royalKnightLorettaCarianManor: {
    name: "Royal Knight Loretta (Carian Manor)",
    image: "../assets/boss-images/royal-knight-loretta.png",
    description:
      "Loretta's spirit form can be found in Caria Manor, which is located at northern Liurnia of the Lakes. The nearest Site of Grace is the Manor Upper Level, but there is also a Marika outside the boss area that you can respawn at.",
    location: "Carian Manor, Liurnia of the Lakes",
    itemDrops: ["Loretta's Greatbow", "Loretta's Slash"],
    runeRewards: "10000 (NG)",
    healthPoints: "",
    affectedBy: ["Bleed", "Frostbite", "Poison", "Scarlet Rot"],
    weakness: [],
    resistance: ["Magic", "Fire", "Holy"],
    immune: [],
    moreInfo: false,
    completed: false,
  },
  royalRevenant: {
    name: "Royal Revenant",
    image: "../assets/boss-images/royal-revenant.png",
    description:
      "Royal Revenant is found within a dungeon at Kingsrealm Ruins, in West Liurnia.",
    location: "Kingsrealm Ruins, Liurnia of the Lakes",
    itemDrops: [],
    runeRewards: "3100 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost"],
    weakness: ["Slash", "Fire", "Lightning"],
    resistance: ["Holy", "Bleed", "Frost", "Scarlet Rot", "Poison"],
    immune: ["Sleep", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  spiritCallerSnailLiurniaOfTheLakes: {
    name: "Spirit-Caller Snail (Liurnia of the Lakes)",
    image: "image/image.png",
    description:
      "Spirit-Caller Snail can be found in the region of Liurnia of the Lakes.",
    location: "Liurnia of the Lakes",
    itemDrops: ["Glintstone Sorcerer"],
    runeRewards: "3000 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost", "Sleep"],
    weakness: [
      "Standard",
      "Strike",
      "Slash",
      "Lightning",
      "Frost",
      "Sleep",
      "Thrust",
    ],
    resistance: ["Magic"],
    immune: ["Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  tibiaMarinerArtist: {
    name: "Tibia Mariner",
    image: "../assets/boss-images/tibia-mariner.png", // Replace with actual image path if necessary
    description:
      "Tibia Mariner is located in Summonwater Village, in the northeast of Limgrave.",
    location: "Artist's Shack (Liurnia of the Lakes)",
    itemDrops: ["Deathroot", "Skeletal Militiaman Spirit Ash"],
    runeRewards: "2400 (NG)",
    healthPoints: "3176 (NG)",
    affectedBy: ["Scarlet Rot"],
    weakness: ["Strike", "Holy"],
    resistance: ["Thrust", "Scarlet Rot"],
    immune: ["Poison", "Bleed", "Frost", "Sleep", "Madness"],
    moreInfo: false,
    completed: false,
  },
  godskinNobleDivineTowerOfLiurnia: {
    name: "Godskin Noble (Divine Tower of Liurnia)",
    image: "../assets/boss-images/godskin-noble.png",
    description:
      "Godskin Noble can be found in Divine Tower of Liurnia, Liurnia of the Lakes.",
    location: "Divine Tower of Liurnia, Liurnia of the Lakes",
    itemDrops: [
      "Godskin Noble Hood",
      "Godskin Noble Robe",
      "Godskin Noble Bracelets",
      "Godskin Noble Trousers",
    ],
    runeRewards: "4810 (NG)",
    healthPoints: "",
    affectedBy: ["Bleed", "Frost", "Scarlet Rot", "Poison"],
    weakness: ["Bleed", "Frost", "Sleep"],
    resistance: ["Fire", "Holy"],
    immune: ["Scarlet Rot", "Poison", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
};
