import { Boss } from "../../models/Bosses";

export const bosses: Record<string, Boss> = {
  bellBearingHunterHermitMerchantsShack: {
    name: "Bell Bearing Hunter (Hermit Merchant's Shack)",
    image: "../assets/boss-images/bell-bearing-hunter.png",
    description:
      "Bell Bearing Hunter can be found at the Hermit Merchant's Shack in Altus Plateau. Each one only spawns at night.",
    location: "Capital Outskirts",
    itemDrops: ["Medicine Peddler's Bell Bearing"],
    runeRewards: "6000 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost"],
    weakness: [],
    resistance: [
      "Standard",
      "Strike",
      "Slash",
      "Fire",
      "Holy",
      "Bleed",
      "Frost",
      "Scarlet Rot",
      "Sleep",
      "Poison",
    ],
    immune: ["Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  crucibleKnightOrdovis: {
    name: "Crucible Knight & Crucible Knight Ordovis",
    image: "path/to/image.png",
    description:
      "From the Capital Rampart site of grace found just after defeating the Draconic Tree Sentinel, head Northwest and then take a sharp turn going South. Follow the cliffside on to your left and jump over the gap and drop down facing Southeast and enter Auriza Hero’s Grave. The double boss fight with Crucible Knight Ordovis is found at the end of this dungeon.",
    location: "Capital Outskirts",
    itemDrops: [
      "Ordovis' Greatsword",
      "Crucible Axe Armor",
      "Crucible Axe Helm",
      "Crucible Gauntlets",
      "Crucible Greaves",
    ],
    runeRewards: "28000 (NG)",
    healthPoints: "", // Not provided in the image
    affectedBy: ["Bleed", "Frost", "Scarlet Rot", "Poison", "Sleep"],
    weakness: ["-", "Scarlet Rot"],
    resistance: ["Bleed", "Frost", "Scarlet Rot", "Sleep", "Poison"],
    immune: ["Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  deathbirdAltusPlateau: {
    name: "Deathbird (Capital Outskirts)",
    image: "image/image.png",
    description:
      "The Deathbird in Altus Plateau can be found in the Altus Plateau region.",
    location: "Capital Outskirts",
    itemDrops: ["Twinbird Kite Shield"],
    runeRewards: "28000 (NG)",
    healthPoints: "",
    affectedBy: ["Scarlet Rot"],
    weakness: ["Strike", "Slash", "Holy"],
    resistance: ["Lightning", "Thrust"],
    immune: ["Bleed", "Frost", "Sleep", "Poison", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  draconicTreeSentinel: {
    name: "Draconic Tree Sentinel",
    image: "path/to/image.png",
    description:
      "Draconic Tree Sentinel can be found at the Capital Outskirts, in the region of Altus Plateau. He will be guarding the northeast entrance to Leyndell, Capital City. There is a nearby Stake of Marika where you can respawn.",
    location: "Capital Outskirts",
    itemDrops: ["Dragon Greatclaw", "Dragonclaw Shield"],
    runeRewards: "50000 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost", "Sleep"],
    weakness: ["Poison"],
    resistance: [
      "Slash",
      "Fire",
      "Lightning",
      "Bleed",
      "Frost",
      "Scarlet Rot",
      "Sleep",
    ],
    immune: ["Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  fellTwins: {
    name: "Fell Twins",
    image: "path/to/image.png",
    description:
      "The Fell Twins can be found while passing the bridge going to the Divine Tower of East Altus. This area will be accessible after defeating Morgott, the Omen King. The Forbidden Lands Site of Grace will be the nearest spawn point.",
    location: "Capital Outskirts",
    itemDrops: ["Omenkiller Rollo"],
    runeRewards: "29000 (NG)",
    healthPoints: "", // Not provided in the image
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost", "Sleep"],
    weakness: ["Slash", "Bleed", "Scarlet Rot", "Poison"],
    resistance: ["Holy"],
    immune: ["Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
  graveWardenDuelistAzuria: {
    name: "Grave Warden Duelist",
    image: "image/image.png",
    description:
      "You can find the Grave Warden Duelist in the Auriza Side Tomb at Capital Outskirts. After arriving through the doors, go down the stairs and you will see a Site of Grace. After 2 sets of stairs, turn right and go down the corridor. Traverse the mist and you will see Grave Warden Duelist waiting for you.",
    location: "Auriza Side Tomb, Capital Outskirts",
    itemDrops: ["Battle Hammer", "Banished Knight Engrave"],
    runeRewards: "1700 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed", "Frost", "Sleep"],
    weakness: ["Slash"],
    resistance: ["Fire", "Holy", "Lightning"],
    immune: ["Madness"],
    moreInfo: false,
    completed: false,
  },
  onyxLord: {
    name: "Onyx Lord",
    image: "../assets/boss-images/onyx.png",
    description:
      "The Onyx Lord can be found deep within the Sealed Tunnel in Altus Plateau. The path to the end of the tunnel is obscured by several Illusory Walls that you will need to attack to reveal the way.",
    location: "Sealed Tunnel, Capital Outskirts",
    itemDrops: ["Onyx Lord's Greatsword"],
    runeRewards: "16000 (NG)",
    healthPoints: "",
    affectedBy: ["Poison", "Scarlet Rot", "Bleed"],
    weakness: ["Bleed", "Scarlet Rot", "Poison"],
    resistance: [],
    immune: ["Frost", "Madness", "Instant Death"],
    moreInfo: false,
    completed: false,
  },
};
